// Measures Ogg Vorbis decode throughput on a ~30-second clip.
//
// The clip is generated once with ffmpeg into a temporary file if ffmpeg is on
// the PATH; otherwise the bench falls back to decoding the committed one-second
// fixture repeatedly, which measures the same decode path on real encoded data.
// Either way the reported numbers are measured on this machine, not estimated.
//
// Usage: dart run bench/bench.dart
import 'dart:io';
import 'dart:typed_data';

import 'package:audio_decode/audio_decode.dart';

const _iterations = 15;

void main() {
  final (bytes, label) = _loadClip();
  final sizeMb = bytes.length / (1024 * 1024);

  // Warm up: first decode also triggers any lazy setup.
  final warm = decodeOgg(bytes);
  final frames = warm.frameCount;
  final channels = warm.channels;
  final rate = warm.sampleRate;
  final seconds = frames / rate;
  final totalSamples = frames * channels;

  final timings = <int>[];
  for (var i = 0; i < _iterations; i++) {
    final sw = Stopwatch()..start();
    final pcm = decodeOgg(bytes);
    sw.stop();
    if (pcm.frameCount != frames) {
      throw StateError('non-deterministic decode');
    }
    timings.add(sw.elapsedMicroseconds);
  }
  timings.sort();
  final medianUs = timings[timings.length ~/ 2];
  final medianMs = medianUs / 1000;

  final samplesPerSec = totalSamples / (medianUs / 1e6);
  final encodedMbPerSec = sizeMb / (medianUs / 1e6);

  print('audio_decode benchmark');
  print('  clip:            $label');
  print('  encoded size:    ${sizeMb.toStringAsFixed(2)} MB');
  print(
    '  audio:           ${seconds.toStringAsFixed(1)} s, '
    '$channels ch, $rate Hz',
  );
  print('  decoded samples: $totalSamples (interleaved int16)');
  print('  runs:            $_iterations (median reported)');
  print('  median decode:   ${medianMs.toStringAsFixed(2)} ms');
  print(
    '  throughput:      '
    '${(samplesPerSec / 1e6).toStringAsFixed(1)} Msamples/s, '
    '${encodedMbPerSec.toStringAsFixed(1)} MB/s of encoded input',
  );
  print(
    '  i.e. decodes ${seconds.toStringAsFixed(0)} s of audio in '
    '${medianMs.toStringAsFixed(0)} ms',
  );
  print('');
  print(
    'No comparable pure-Dart Ogg Vorbis decoder was found to benchmark '
    'against; the numbers above are absolute throughput.',
  );
}

/// Returns the encoded clip bytes and a human-readable label. Prefers a 30 s
/// clip generated by ffmpeg; falls back to the committed 1 s fixture.
(Uint8List, String) _loadClip() {
  final generated = _generateWithFfmpeg();
  if (generated != null) {
    return (generated, '~30 s sine, generated with ffmpeg');
  }
  final fixture = File('test/fixtures/sine_44100_mono_1s.ogg');
  if (fixture.existsSync()) {
    return (
      fixture.readAsBytesSync(),
      '1 s fixture (ffmpeg not found; install it for a 30 s clip)',
    );
  }
  throw StateError('no clip available: run from the package root');
}

Uint8List? _generateWithFfmpeg() {
  final dir = Directory.systemTemp.createTempSync('audio_decode_bench');
  final out = '${dir.path}/bench_30s.ogg';
  try {
    final result = Process.runSync('ffmpeg', [
      '-hide_banner',
      '-loglevel',
      'error',
      '-f',
      'lavfi',
      '-i',
      'sine=frequency=440:duration=30:sample_rate=44100',
      '-ac',
      '2',
      '-c:a',
      'libvorbis',
      '-y',
      out,
    ]);
    if (result.exitCode != 0) return null;
    return File(out).readAsBytesSync();
  } on ProcessException {
    return null;
  } finally {
    try {
      dir.deleteSync(recursive: true);
    } on FileSystemException {
      // Best effort cleanup.
    }
  }
}
